/**:
  ros__parameters:
    robot_description_planning:
      default_velocity_scaling_factor: 0.3
      default_acceleration_scaling_factor: 0.3
    joint_limits:
      lbr_iiwa_joint_1:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
      lbr_iiwa_joint_2:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
      lbr_iiwa_joint_3:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
      lbr_iiwa_joint_4:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
      lbr_iiwa_joint_5:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
      lbr_iiwa_joint_6:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
      lbr_iiwa_joint_7:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 1.0
