/**:
  ros__parameters:
    robot_description_planning:
      default_velocity_scaling_factor: 0.4
      default_acceleration_scaling_factor: 0.4
    joint_limits:
      joint1:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 1.0
      joint2:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 1.0
